# Overrides
Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": ()
    "%w": ()

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true

Rails:
  Enabled: true

Metrics/LineLength:
  Exclude:
  - config/initializers/backtrace_silencers.rb
  - bin/*
  Max: 120

Style/MixinUsage:
  Exclude:
  - bin/*

Airbnb/SimpleModifierConditional:
  Exclude:
  - bin/*

